### ISSUE TITLE
Want to contribute a PR

### ISSUE THREAD

**Issue by bjesuiter** [simonepri/project-version#5]
Hello simonepri, 

I want to contribute a cli mode to your package, complete with comments and README adjustments. 
But I'm not able to push a new branch to this repo to create a PR. 
I could make a fork and create a PR from that, but this seems a little bit overkill. 

Can you tell me how I can create a PR for you? 
As a last resort you could invite me to your repo, then I'll be able to use ssh instead of this https token thing.

**Comment by simonepri** [comment]
Hi @bjesuiter,
Thank you for the interest.

Actually I was thinking to improve this package asap, since there are some bugs that needs to be fixed.

If you want to contribute you can fork the project and then create a PR here.
Or you can just use the web editor inside GitHub to submit the PR.

Can you share with me what kind of improvements are you planning to do?

**Comment by bjesuiter** [comment]
I've create a PR for you, I think this is easier than me trying to explain my changes :) 

In general, I've added the possibility to call this lib via cli to be able to use it in npm scripts. 
I also wanted to fix the security problems shown after npm install, but since we don't have a lockfile, I did not want to make this big of a change :) 

May I ask, what bugs do you want to fix?

**Comment by simonepri** [comment]
@bjesuiter the [use of the `npm_package_version` environment](https://github.com/simonepri/project-version/commit/3ddc786bdcc4d0e5c82b59422845d007b936ede9#diff-168726dbe96b3ce427e7fedce31bb0bcL7) variable did not allowed the package to be used as nested dependency.
This has been fixed in 1.1.0
